### サインアップ
# @name signup
POST {{base_url}}/signup
Content-Type: application/json

{
    "email": "s.datsukan@gmail.com"
}

### サインイン
# @name signin
POST {{base_url}}/signin
Content-Type: application/json

{
    "email": "sample@example.com",
    "password": "sample-password"
}

###

@user_id = {{signin.response.body.id}}
@session_token = {{signin.response.body.session_token}}

### パスワード変更
# @name change_password
POST {{base_url}}/password/reset
Content-Type: application/json

{
    "token": "sample-token",
    "password": "sample-password"
}

### 学事の新規作成（前の要素なし）
# @name create
POST {{base_url}}/schedules
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
    "name": "テストスケジュール",
    "starts_at": "2024-06-01 00:00:00",
    "ends_at": "2024-08-15 00:00:00",
    "color": "white",
    "type": "master"
}

### 受講の新規作成（前の要素なし）
# @name create
POST {{base_url}}/schedules
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
    "name": "テストスケジュール",
    "starts_at": "2024-06-01 00:00:00",
    "ends_at": "2024-08-15 00:00:00",
    "color": "white",
    "type": "custom"
}

### 学事の新規作成（前の要素あり）
# @name create
POST {{base_url}}/schedules
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
    "name": "テストスケジュール",
    "starts_at": "2024-06-01 00:00:00",
    "ends_at": "2024-08-15 00:00:00",
    "color": "white",
    "type": "master",
    "order": 1
}

### 受講の新規作成（前の要素あり）
# @name create
POST {{base_url}}/schedules
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
    "name": "テストスケジュール",
    "starts_at": "2024-06-01 00:00:00",
    "ends_at": "2024-08-15 00:00:00",
    "color": "white",
    "type": "custom",
    "order": 1
}

### 一覧取得
# @name get_list
GET {{base_url}}/users/{{user_id}}/schedules
Authorization: Bearer {{session_token}}

### 個別取得

@schedule_id = {{create.response.body.id}}

# @name get
GET {{base_url}}/schedules/{{schedule_id}}
Authorization: Bearer {{session_token}}

### 更新
# @name update
PUT {{base_url}}/schedules/{{schedule_id}}
Authorization: Bearer {{session_token}}
Content-Type: application/json

{
    "name": "変更後テストスケジュール",
    "starts_at": "2024-06-02 00:00:00",
    "ends_at": "2024-08-16 00:00:00",
    "color": "black",
    "type": "custom"
}

### 削除
# @name delete
DELETE {{base_url}}/schedules/{{schedule_id}}
Authorization: Bearer {{session_token}}
