PasswordSetFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: PasswordSetFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: PasswordSetFunction
    CodeUri: cmd/auth/password_set
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiPasswordSet:
        Type: Api
        Properties:
          Path: /password/set
          Method: POST
          RestApiId: !Ref Api
    Environment:
      Variables:
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
PasswordSetFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt PasswordSetFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
PasswordSetFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${PasswordSetFunction}
