SignUpFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: SignUpFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: SignUpFunction
    CodeUri: cmd/auth/signup
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiSignUp:
        Type: Api
        Properties:
          Path: /signup
          Method: POST
          RestApiId: !Ref Api
    Environment:
      Variables:
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
SignUpFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt SignUpFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
SignUpFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${SignUpFunction}
