SignInFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: SignInFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: SignInFunction
    CodeUri: cmd/auth/signin
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiSignIn:
        Type: Api
        Properties:
          Path: /signin
          Method: POST
          RestApiId: !Ref Api
    Environment:
      Variables:
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
        SESSION_TABLE_NAME: !Ref SessionTable
        SESSION_TABLE_ARN: !GetAtt SessionTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
      - DynamoDBCrudPolicy:
          TableName: !Ref SessionTable
SignInFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt SignInFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
SignInFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${SignInFunction}
