DeleteUserFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: DeleteUserFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: DeleteUserFunction
    CodeUri: cmd/user/delete
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiDeleteUser:
        Type: Api
        Properties:
          Path: /users/{user_id}
          Method: DELETE
          RestApiId: !Ref Api
    Environment:
      Variables:
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
DeleteUserFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt DeleteUserFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
DeleteUserFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${DeleteUserFunction}
