SubjectTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: AttendancePlan_Subject
    AttributeDefinitions:
      - AttributeName: ID
        AttributeType: S
      - AttributeName: UserID
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: ID
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: UserID-index
        KeySchema:
          - AttributeName: UserID
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
