DeleteScheduleFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: DeleteScheduleFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: DeleteScheduleFunction
    CodeUri: cmd/schedule/delete
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiDeleteSchedule:
        Type: Api
        Properties:
          Path: /schedules/{schedule_id}
          Method: DELETE
          RestApiId: !Ref Api
    Environment:
      Variables:
        SCHEDULE_TABLE_NAME: !Ref ScheduleTable
        SCHEDULE_TABLE_ARN: !GetAtt ScheduleTable.Arn
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
        SESSION_TABLE_NAME: !Ref SessionTable
        SESSION_TABLE_ARN: !GetAtt SessionTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ScheduleTable
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
      - DynamoDBCrudPolicy:
          TableName: !Ref SessionTable
DeleteScheduleFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt DeleteScheduleFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
DeleteScheduleFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${DeleteScheduleFunction}
