PostScheduleFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: PostScheduleFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: PostScheduleFunction
    CodeUri: cmd/schedule/post
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiPostSchedule:
        Type: Api
        Properties:
          Path: /schedules
          Method: POST
          RestApiId: !Ref Api
    Environment:
      Variables:
        SCHEDULE_TABLE_NAME: !Ref ScheduleTable
        SCHEDULE_TABLE_ARN: !GetAtt ScheduleTable.Arn
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ScheduleTable
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
PostScheduleFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt PostScheduleFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
PostScheduleFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${PostScheduleFunction}
