PostBulkScheduleFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: PostBulkScheduleFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: PostBulkScheduleFunction
    CodeUri: cmd/schedule/post_bulk
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiPostBulkSchedule:
        Type: Api
        Properties:
          Path: /schedules/bulk
          Method: POST
          RestApiId: !Ref Api
    Environment:
      Variables:
        SCHEDULE_TABLE_NAME: !Ref ScheduleTable
        SCHEDULE_TABLE_ARN: !GetAtt ScheduleTable.Arn
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ScheduleTable
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
PostBulkScheduleFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt PostBulkScheduleFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
PostBulkScheduleFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${PostBulkScheduleFunction}
