PutBulkScheduleFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: PutBulkScheduleFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: PutBulkScheduleFunction
    CodeUri: cmd/schedule/put_bulk
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiPutBulkSchedule:
        Type: Api
        Properties:
          Path: /schedules/bulk
          Method: PUT
          RestApiId: !Ref Api
    Environment:
      Variables:
        SCHEDULE_TABLE_NAME: !Ref ScheduleTable
        SCHEDULE_TABLE_ARN: !GetAtt ScheduleTable.Arn
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ScheduleTable
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
PutBulkScheduleFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt PutBulkScheduleFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
PutBulkScheduleFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${PutBulkScheduleFunction}
