### 入力不正 IDが不正
PUT {{base_url}}/schedules/dummy-id
Content-Type: application/json

{
    "name": "テストスケジュール",
    "starts_at": "2024-06-01 00:00:00",
    "ends_at": "2024-08-15 00:00:00",
    "color": "white",
    "type": "master"
}
