DeleteSubjectFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: DeleteSubjectFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: DeleteSubjectFunction
    CodeUri: cmd/subject/delete
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiDeleteSubject:
        Type: Api
        Properties:
          Path: /subjects/{subject_id}
          Method: DELETE
          RestApiId: !Ref Api
    Environment:
      Variables:
        SUBJECT_TABLE_NAME: !Ref SubjectTable
        SUBJECT_TABLE_ARN: !GetAtt SubjectTable.Arn
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref SubjectTable
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
DeleteSubjectFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt DeleteSubjectFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
DeleteSubjectFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${DeleteSubjectFunction}
