PostSubjectFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: go1.x
  Properties:
    FunctionName: PostSubjectFunction
    Description: !Sub
      - Stack ${AWS::StackName} Function ${ResourceName}
      - ResourceName: PostSubjectFunction
    CodeUri: cmd/subject/post
    Handler: bootstrap
    Runtime: provided.al2023
    MemorySize: 128
    Timeout: 30
    Tracing: Active
    Events:
      ApiPostSubject:
        Type: Api
        Properties:
          Path: /subjects
          Method: POST
          RestApiId: !Ref Api
    Environment:
      Variables:
        SUBJECT_TABLE_NAME: !Ref SubjectTable
        SUBJECT_TABLE_ARN: !GetAtt SubjectTable.Arn
        USER_TABLE_NAME: !Ref UserTable
        USER_TABLE_ARN: !GetAtt UserTable.Arn
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref SubjectTable
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
PostSubjectFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !GetAtt PostSubjectFunction.Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
PostSubjectFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DeletionPolicy: Retain
  Properties:
    LogGroupName: !Sub /aws/lambda/${PostSubjectFunction}
